qemu-zcu102: Give better debug when QEMU exits with an error
If qemu exits with non-zero status, print a message and delay for a bit
before closing the tmux window.

Signed-off-by: Bill Mills <bill.mills@linaro.org>

diff --git a/qemu-zcu102/bin/qemu-zcu102 b/qemu-zcu102/bin/qemu-zcu102
--- a/qemu-zcu102/bin/qemu-zcu102
+++ b/qemu-zcu102/bin/qemu-zcu102
@@ -100,6 +100,10 @@ do_start-qemu() {
     $SYS_ROOT/usr/bin/qemu-system-aarch64-multiarch \
         $APU_ARGS \
         -pmu-args "$PMU_ARGS"
+    if [ $? -ne 0 ]; then
+        echo "QEMU error exit $?"
+        sleep 5
+    fi
     tmux-kill
 }
 
